### ISSUE TITLE
Undefined method `message' for false:FalseClass (NoMethodError)

### ISSUE THREAD

**Issue by sebastianzillessen** [NARKOZ/gitlab#190]
When I try to run pronto on a private hosted gitlab, I get the following error:

The GitLab version we are running is: GitLab Community Edition 8.5.5

Does anyone have any ideas where this could come from?

```
pronto run -f gitlab -c origin/master
Running Pronto::JSHint
Running Pronto::Rubocop
/Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/gitlab-3.6.1/lib/gitlab/request.rb:117:in `error_message': undefined method `message' for false:FalseClass (NoMethodError)
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/gitlab-3.6.1/lib/gitlab/request.rb:75:in `validate'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/gitlab-3.6.1/lib/gitlab/request.rb:43:in `get'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/gitlab-3.6.1/lib/gitlab/client/commits.rb:61:in `commit_comments'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/gitlab.rb:11:in `commit_comments'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/formatter/gitlab_formatter.rb:22:in `create_comment'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/formatter/gitlab_formatter.rb:8:in `block in format'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/formatter/gitlab_formatter.rb:7:in `map'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/formatter/gitlab_formatter.rb:7:in `format'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto.rb:45:in `block in run'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto.rb:44:in `each'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto.rb:44:in `run'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/cli.rb:52:in `run'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/bin/pronto:6:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/bin/pronto:23:in `load'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/bin/pronto:23:in `<main>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/bin/ruby_executable_hooks:15:in `eval'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by asedge** [comment]
Could you try printing `response` here to see what it looks like?
https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/request.rb#L116

**Comment by sebastianzillessen** [comment]
I added `puts "response #{response.inspect}"`.

Result is:

So the response seems to be "false" because of an internal 500 error.

```
pronto run -f gitlab -c origin/master
Running Pronto::JSHint
Running Pronto::Rubocop
response #<HTTParty::Response:0x0 parsed_response=false, @response=#<Net::HTTPInternalServerError 500 Internal Server Error readbody=true>, @headers={"server"⇒["nginx"], "date"⇒["Thu, 07 Apr 2016 12:28:10 GMT"], "content-type"=>["text/html; charset=utf-8"], "content-length"=>["48"], "connection"=>["close"], "cache-control"=>["no-cache, no-store, max-age=0, must-revalidate"], "expires"=>["Fri, 01 Jan 1990 00:00:00 GMT"], "pragma"=>["no-cache"], "status"=>["500 Internal Server Error"], "x-request-id"=>["d565eadb-be27-4843-bbf5-fc7fb6457769"], "x-runtime"=>["0.076593"]}>
/Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/gitlab-3.6.1/lib/gitlab/request.rb:118:in `error_message': undefined method `message' for false:FalseClass (NoMethodError)
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/gitlab-3.6.1/lib/gitlab/request.rb:75:in `validate'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/gitlab-3.6.1/lib/gitlab/request.rb:43:in `get'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/gitlab-3.6.1/lib/gitlab/client/commits.rb:61:in `commit_comments'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/gitlab.rb:11:in `commit_comments'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/formatter/gitlab_formatter.rb:22:in `create_comment'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/formatter/gitlab_formatter.rb:8:in `block in format'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/formatter/gitlab_formatter.rb:7:in `map'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/formatter/gitlab_formatter.rb:7:in `format'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto.rb:45:in `block in run'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto.rb:44:in `each'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto.rb:44:in `run'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/cli.rb:52:in `run'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/bin/pronto:6:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/bin/pronto:23:in `load'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/bin/pronto:23:in `<main>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/bin/ruby_executable_hooks:15:in `eval'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/bin/ruby_executable_hooks:15:in `<main>'pronto run -f gitlab -c origin/master
Running Pronto::JSHint
Running Pronto::Rubocop
response #<HTTParty::Response:0x0 parsed_response=false, @response=#<Net::HTTPInternalServerError 500 Internal Server Error readbody=true>, @headers={"server"⇒["nginx"], "date"⇒["Thu, 07 Apr 2016 12:28:10 GMT"], "content-type"=>["text/html; charset=utf-8"], "content-length"=>["48"], "connection"=>["close"], "cache-control"=>["no-cache, no-store, max-age=0, must-revalidate"], "expires"=>["Fri, 01 Jan 1990 00:00:00 GMT"], "pragma"=>["no-cache"], "status"=>["500 Internal Server Error"], "x-request-id"=>["d565eadb-be27-4843-bbf5-fc7fb6457769"], "x-runtime"=>["0.076593"]}>
/Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/gitlab-3.6.1/lib/gitlab/request.rb:118:in `error_message': undefined method `message' for false:FalseClass (NoMethodError)
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/gitlab-3.6.1/lib/gitlab/request.rb:75:in `validate'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/gitlab-3.6.1/lib/gitlab/request.rb:43:in `get'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/gitlab-3.6.1/lib/gitlab/client/commits.rb:61:in `commit_comments'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/gitlab.rb:11:in `commit_comments'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/formatter/gitlab_formatter.rb:22:in `create_comment'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/formatter/gitlab_formatter.rb:8:in `block in format'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/formatter/gitlab_formatter.rb:7:in `map'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/formatter/gitlab_formatter.rb:7:in `format'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto.rb:45:in `block in run'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto.rb:44:in `each'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto.rb:44:in `run'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/lib/pronto/cli.rb:52:in `run'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/pronto-0.6.0/bin/pronto:6:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/bin/pronto:23:in `load'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/bin/pronto:23:in `<main>'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/bin/ruby_executable_hooks:15:in `eval'
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@project/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by asedge** [comment]
Could I trouble you to check one more thing?  Could you see what `body` is set to here?

https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/request.rb#L17

You should probably also check out the server logs to see why you're getting a 500 error.

**Comment by sebastianzillessen** [comment]
So I entered:

```
def self.parse(body)
      puts "body is #{body}"
      body = decode(body)

```

Output is:

```
response #<HTTParty::Response:0x0 parsed_response=false, @response=#<Net::HTTPInternalServerError 500 Internal Server Error readbody=true>, @headers={"server"⇒["nginx"], "date"⇒["Thu, 07 Apr 2016 20:01:19 GMT"], "content-type"=>["text/html; charset=utf-8"], "content-length"=>["48"], "connection"=>["close"], "cache-control"=>["no-cache, no-store, max-age=0, must-revalidate"], "expires"=>["Fri, 01 Jan 1990 00:00:00 GMT"], "pragma"=>["no-cache"], "status"=>["500 Internal Server Error"], "x-request-id"=>["7008bea2-f138-4a40-9677-49d5f95749db"], "x-runtime"=>["0.387421"]}>
```

Interesting fact is, that the expires is attribute is set to 01. Jan 1990. 

Notable as well is, that I had to deactivate the SSL check to get a connection at all by 

```
export GITLAB_API_HTTPARTY_OPTIONS="{verify: false}"
```
in the terminal.

Unfortunately I don't have access to the server right now, so I can't check the logs. Anything we could do from here?

**Comment by asedge** [comment]
Output should start with `body is` not `response`, right?

**Comment by sebastianzillessen** [comment]
So true! Sorry, its getting late here...

```
Running Pronto::JSHint
Running Pronto::Rubocop
body is 
body is 
body is 
response #<HTTParty::Response:0x0 parsed_response=false, @response=#<Net::HTTPInternalServerError 500 Internal Server Error readbody=true>, @headers={"server"=>["nginx"], "date"=>["Thu, 07 Apr 2016 20:22:00 GMT"], "content-type"=>["text/html; charset=utf-8"], "content-length"=>["48"], "connection"=>["close"], "cache-control"=>["no-cache, no-store, max-age=0, must-revalidate"], "expires"=>["Fri, 01 Jan 1990 00:00:00 GMT"], "pragma"=>["no-cache"], "status"=>["500 Internal Server Error"], "x-request-id"=>["fa760704-43a7-4d6a-9055-e0abd955c2b4"], "x-runtime"=>["0.218661"]}>
body is 
/Users/user/.rvm/gems/ruby-2.0.0-p643@project/gems/gitlab-3.6.1/lib/gitlab/request.rb:119:in `error_message': undefined method `message' for false:FalseClass (NoMethodError)
	from /Users/user/.rvm/gems/ruby-2.0.0-p643@ project/gems/gitlab-3.6.1/lib/g
    ....
```

**Comment by asedge** [comment]
No worries.

The output isn't totally unexpected though.  I was just hoping that the `false` was coming from the server but it's not.  I wanted to see if we could handle this case better and we probably can.

Unfortunately, the only way to tell what's causing the 500 error would be to hop on the server and check the logs.

**Comment by sebastianzillessen** [comment]
Alright, I hope to get the error log tomorrow from my colleague. I'll let u know!

**Comment by sebastianzillessen** [comment]
So I hope we got the right logs:

```
zgrep -A 15 -B 10 'Completed 500' production.log*
Completed 200 OK in 61ms (Views: 0.3ms | ActiveRecord: 4.8ms)
Started GET "/<CONFIDENTIAL>/<CONFIDENTIAL>/notes?target_id=5608&target_type=merge_request&last_fetched_at=1460030077" for 127.0.0.1 at 2016-04-07 13:54:52 +0200
Processing by Projects::NotesController#index as JSON
  Parameters: {"target_id"=>"5608", "target_type"=>"merge_request", "last_fetched_at"=>"1460030077", "namespace_id"=>"<CONFIDENTIAL>", "project_id"=>"<CONFIDENTIAL>"}
Completed 200 OK in 73ms (Views: 0.3ms | ActiveRecord: 6.4ms)
Started POST "/api/v3/internal/allowed" for 127.0.0.1 at 2016-04-07 13:55:00 +0200
Started POST "/api/v3/internal/allowed" for 127.0.0.1 at 2016-04-07 13:55:00 +0200
Started GET "/projects/<CONFIDENTIAL>%2Fstandard/repository/commits/8d8c7e332769b2ebdac9216265dc6fce1195a90e/comments?per_page=500" for 127.0.0.1 at 2016-04-07 13:55:00 +0200
Processing by NamespacesController#show as JSON
  Parameters: {"per_page"=>"500", "id"=>"projects/<CONFIDENTIAL>/standard/repository/commits/8d8c7e332769b2ebdac9216265dc6fce1195a90e/comments"}
Completed 500 Internal Server Error in 52ms (ActiveRecord: 5.5ms)

ActionView::MissingTemplate (Missing template opt/gitlab/embedded/service/gitlab-rails/public/404 with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :haml]}. Searched in:
  * "/opt/gitlab/embedded/service/gitlab-rails/app/views"
  * "/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/kaminari-0.16.3/app/views"
  * "/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/doorkeeper-2.2.2/app/views"
  * "/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-3.5.4/app/views"
  * "/var/opt/gitlab/gitlab-rails/working"
  * "/"
):
  app/controllers/application_controller.rb:183:in `render_404'
  app/controllers/namespaces_controller.rb:22:in `show'
....

```
*Note: * As this is a company server, I removed the project names.

So it looks like the `gitlab` gem is trying to access a view as JSON which is not available.

What do you think?

**Comment by bikolya** [comment]
@sebastianzillessen Are you sure you're using API endpoint and not gitlab itself? I had the same issue when I tried to access API, but forgot about /api/v3/ part.

**Comment by asedge** [comment]
@sebastianzillessen Please verify that the `endpoint` is set correctly.
```
Started GET "/projects/<CONFIDENTIAL>%2Fstandard/repository/commits/8d8c7e332769b2ebdac9216265dc6fce1195a90e/comments?per_page=500" for 127.0.0.1 at 2016-04-07 13:55:00 +0200
```
I would expect this GET to start with /api/v3, as @bikolya (thanks!) pointed out.

**Comment by sebastianzillessen** [comment]
So true, sorry for the inconvenience!

**Comment by gommo** [comment]
I seem to be getting this now possibly because of gitlab 8.17 ?
