### ISSUE TITLE
create_branch fails

### ISSUE THREAD

**Issue by danhalligan** [NARKOZ/gitlab#322]
When using the code:
```
Gitlab.create_branch(201, "newbranch", "master")
```

I get the error 
```
Gitlab::Error::BadRequest: Server responded with code 400, message: branch_name is missing. Request URI: http://gitlab.xxxxx.com/api/v3/projects/201/repository/branches
	from /usr/local/rvm/gems/ruby-2.4.0/gems/gitlab-4.2.0/lib/gitlab/request.rb:80:in `validate'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/gitlab-4.2.0/lib/gitlab/request.rb:49:in `post'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/gitlab-4.2.0/lib/gitlab/client/branches.rb:79:in `create_branch'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/gitlab-4.2.0/lib/gitlab.rb:25:in `method_missing'
	from (irb):2
	from bin/console:14:in `<main>'
```

However, this curl command creates the requested branch OK:
```
curl --request POST --header "PRIVATE-TOKEN: XXXXXX" "http://gitlab.xxxxxx.com/api/v4/projects/201/repository/branches?branch=newbranch&ref=master"
```
As does this:
```
curl --request POST --header "PRIVATE-TOKEN: XXXXX" "http://gitlab.xxxxx.com/api/v4/projects/201/repository/branches" -d '{"branch":"newbranch","ref":"master"}'  -H "Content-Type: application/json"
```

However, replacing "v4" with "v3" in the above urls returns the error message:
```
{"error":"branch_name is missing"}
```

Specifying `branch_name` instead of `branch` solves the error with the v3 API.

**Comment by danhalligan** [comment]
OK - after a bit of investigation, it looks like I need to set my endpoint to 
```
http://gitlab.xxxxx.com/api/v4
```
instead of 
```
http://gitlab.xxxxx.com/api/v3
```
