### ISSUE TITLE
Getting "branch_name is missing" error when creating commit

### ISSUE THREAD

**Issue by inem** [NARKOZ/gitlab#326]
Obviously the branch is provided:

```
commit = gitlab.create_commit(project.id, 'master', 'initial commit', [{action: 'create', file_path: '/index.html', content: "01"}])

/Users/inem/.rvm/gems/ruby-2.4.0/gems/gitlab-4.2.0/lib/gitlab/request.rb:80:in `validate': Server responded with code 400, message: branch_name is missing. Request URI: https://gitlab.com/api/v3/projects/4413953/repository/commits (Gitlab::Error::BadRequest)
        from /Users/inem/.rvm/gems/ruby-2.4.0/gems/gitlab-4.2.0/lib/gitlab/request.rb:49:in `post'
        from /Users/inem/.rvm/gems/ruby-2.4.0/gems/gitlab-4.2.0/lib/gitlab/client/commits.rb:143:in `create_commit'
        from 01.rb:78:in `<main>'
```

I added `puts options.inspect` inside `Gitlab::Request#post`, and it seem to work as expected:

```
{:body=>{:branch=>"master", :commit_message=>"initial commit", :actions=>[{:action=>"create", :file_path=>"/index.html", :content=>"01"}]}
```

Does this mean that GitLab's API have changed, and the gem doesn't follow it yet?

**Comment by inem** [comment]
I've just tried it with [the sample code from specs](https://github.com/NARKOZ/gitlab/blob/master/spec/gitlab/client/commits_spec.rb#L138-L168) and got the same error: Server responded with code 400, message: branch_name is missing. Request URI: https://gitlab.com/api/v3/projects/4418686/repository/commits (Gitlab::Error::BadRequest)

**Comment by inem** [comment]
Oh, figured it out finally! I forgot to specify v4 in endpoint. Closing this
