### ISSUE TITLE
Error Deleting an image from registry

### ISSUE THREAD

**Issue by Marvalero** [NARKOZ/gitlab#334]
So I wrote an script to remove old images on the registry.
When deleting the image, Gitlab replies with 422:
```ruby
client.delete(image.destroy_path)
```
I think there is a problem with authentication with the registry when using delete. Is there a way to do this?

Gitlab logs:
```
Started DELETE "/backend/application/registry/repository/6/tags/226aafd289ddcac3512c56b5c4cadce3a83ba09b" for 10.0.2.64 at 2017-11-15 17:20:08 +0000
Processing by Projects::Registry::TagsController#destroy as JSON
  Parameters: {"namespace_id"=>"backend", "project_id"=>"application", "repository_id"=>"6", "id"=>"226aafd289ddcac3512c56b5c4cadce3a83ba09b"}
Can't verify CSRF token authenticity
Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms)

ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  lib/gitlab/middleware/multipart.rb:93:in `call'
  lib/gitlab/request_profiler/middleware.rb:14:in `call'
  lib/gitlab/jira/middleware.rb:15:in `call'
  lib/gitlab/middleware/go.rb:17:in `call'
  lib/gitlab/etag_caching/middleware.rb:11:in `call'
  lib/gitlab/middleware/read_only.rb:30:in `call'
  lib/gitlab/request_context.rb:18:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'
```

Script:
```ruby
require "date"

REPOSITORIES = [
  "backend/application"
]
MONTH_RETENTION = 2
IMAGE_NAME_LEN = 40
GITLAB_PRIVATE_TOKEN = ENV["GITLAB_PRIVATE_TOKEN"]

class Cleaner
  def self.call
    REPOSITORIES.each do |repository|
      puts "-------------------------------------------------"
      puts "Clean repository=#{repository}"
      images = DeleteImages.call(
                 ImagesFilter.call(
                   ImagesCollection.all(repository)))
      puts ""
    end
  end
end

class RegistryIdCalculator
  def self.call(repository)
    GitlabClient.call.get("/#{repository}/container_registry.json").first.id
  end
end

class ImagesCollection
  def self.all(repository)
    images = []
    registry_url = "/#{repository}/registry/repository/#{RegistryIdCalculator.call(repository)}/tags"
    GitlabClient.call.get(registry_url).each_page do |page|
      images << page
    end
    puts "Fetch registry_url=#{registry_url}, images.count=#{images.flatten.count}"
    images.flatten
  end
end

class ImagesFilter
  def self.call(images)
    new.call(images)
  end

  def call(images)
    images.select do |image|
      (between_retention_period(image) && allowed_name(image)).tap do |remove|
        puts "Image #{image.name} #{image.created_at} remove?=#{remove}"
      end
    end
  end

  private

  def allowed_name(image)
    image.name.length == IMAGE_NAME_LEN
  end

  def between_retention_period(image)
    return true unless image.created_at
    d  = Date.parse(image.created_at)
    (d.year < year_filter ||
      ( d.year == year_filter && d.month < month_filter ) ||
      ( d.year == year_filter && d.month == month_filter  && d.day <= day_filter))
  end

  def year_filter
    @year_filter ||= Time.now.year
  end

  def month_filter
    @month_filter ||= Time.now.month - MONTH_RETENTION
  end

  def day_filter
    @day_filter ||= Time.now.day
  end
end

class DeleteImages
  def self.call(images)
    images.each do |im|
      begin
        puts "remove #{im.destroy_path}"
        GitlabClient.call.delete(im.destroy_path)
      rescue => err
        puts "Error deleting image err=#{err.inspect}"
      end
    end
  end
end

class GitlabClient
  def self.call
    require 'gitlab'
    @gitlab_client ||= Gitlab.client(endpoint: 'https://gitlab.quiqup.com', private_token: GITLAB_PRIVATE_TOKEN)
  end
end

Cleaner.call

```

**Comment by NARKOZ** [comment]
I think you're passing a wrong API endpoint to gitlab client. It should end with `/api/v4`.
