### ISSUE TITLE
invalid token causes stack trace

### ISSUE THREAD

**Issue by logicminds** [NARKOZ/gitlab#359]
When calling Gitlab.deploy_keys with a token then is no loner valid I get the following result.  

```
from /opt/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.3.0/lib/gitlab/error.rb:40:in `build_error_message'
        from /opt/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.3.0/lib/gitlab/error.rb:16:in `initialize'
        from /opt/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:64:in `exception'
        from /opt/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:64:in `raise'
        from /opt/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:64:in `validate'
        from /opt/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:44:in `block (2 levels) in <class:Request>'
        from /opt/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.3.0/lib/gitlab/client/projects.rb:340:in `deploy_keys'
        from /opt/embedded/lib/ruby/gems/2.4.0/gems/gitlab-4.3.0/lib/gitlab.rb:25:in `method_missing'
```

The value of the hash passed into ObjectifiedHash is

`{"error"=>"invalid_token", "error_description"=>"Token is expired. You can either do re-authorization or token refresh."}`

Note: this only happens with an expired token

**Comment by johnmcconnell** [comment]
```bash
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/home/john/.rvm/gems/ruby-2.3.6/gems/gitlab-4.3.0/lib/gitlab/objectified_hash.rb:26:in `method_missing'
/home/john/.rvm/gems/ruby-2.3.6/gems/gitlab-4.3.0/lib/gitlab/error.rb:40:in `build_error_message'
/home/john/.rvm/gems/ruby-2.3.6/gems/gitlab-4.3.0/lib/gitlab/error.rb:16:in `initialize'
/home/john/.rvm/gems/ruby-2.3.6/gems/gitlab-4.3.0/lib/gitlab/request.rb:64:in `exception'
/home/john/.rvm/gems/ruby-2.3.6/gems/gitlab-4.3.0/lib/gitlab/request.rb:64:in `raise'
/home/john/.rvm/gems/ruby-2.3.6/gems/gitlab-4.3.0/lib/gitlab/request.rb:64:in `validate'
/home/john/.rvm/gems/ruby-2.3.6/gems/gitlab-4.3.0/lib/gitlab/request.rb:44:in `block (2 levels) in <class:Request>'
/home/john/.rvm/gems/ruby-2.3.6/gems/gitlab-4.3.0/lib/gitlab/client/groups.rb:27:in `group'
/home/john/dev/gitlab.com/cogli/gitlab-reporter/lib/gitlab/reporter.rb:26:in `build_report!'
/home/john/dev/gitlab.com/cogli/gitlab-reporter/Rakefile:13:in `block in <top (required)>'
/home/john/.rvm/gems/ruby-2.3.6/bin/ruby_executable_hooks:15:in `eval'
/home/john/.rvm/gems/ruby-2.3.6/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => build_report
(See full trace by running task with --trace)
```

**Comment by asedge** [comment]
OK, I think I figured this out.  On [this line](https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/error.rb#L40) the else condition of the ternary is `parsed_response['message']`.  The problem is that `Gitlab::ObjectifiedHash` does not define a method for `[]`.  `method_missing` is then called and it only expects one parameter but calling `foo['message']` sends 2 parameters to `method_missing`: `[]` and `message`.

In my local testing I defined `[]` and the `ArgumentError` went away.  The question is should `ObjectifiedHash` actually support Hash-like access in the way attempted on that line?  If the answer is yes then it seems clear we need to define `[]`.  If not, perhaps obviously, we shouldn't be trying to access it that way and it should be rewritten the way it was intended to be used.  @NARKOZ do you have an opinion on this?

**Comment by NARKOZ** [comment]
>The question is should ObjectifiedHash actually support Hash-like access in the way attempted on that line?

No.

Also seems like a duplicate of #388

**Comment by asedge** [comment]
I pushed a branch with a fix. @logicminds @johnmcconnell - it would be nice if one of you could try it out. Thanks.
