### ISSUE TITLE
Exception on error in response code

### ISSUE THREAD

**Issue by Apelsinka223** [NARKOZ/gitlab#391]
Hi, I use pronto with gitlab, and I guess it returns one of this errors on comments post https://github.com/NARKOZ/gitlab/blob/2eb3a093419fcf367cbd19576c116febfbd17d2e/lib/gitlab/request.rb#L52-L61
But there are exception when it decodes the error message
```
/lib/gems/2.3.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:37:in `rescue in decode': The response is not a valid JSON (Gitlab::Error::Parsing)
	from /var/lib/gems/2.3.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:35:in `decode'
	from /var/lib/gems/2.3.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:16:in `parse'
	from /var/lib/gems/2.3.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:10:in `block in <class:Request>'
	from /var/lib/gems/2.3.0/gems/httparty-0.16.2/lib/httparty/request.rb:391:in `parse_response'
	from /var/lib/gems/2.3.0/gems/httparty-0.16.2/lib/httparty/request.rb:359:in `block in handle_response'
	from /var/lib/gems/2.3.0/gems/httparty-0.16.2/lib/httparty/response.rb:25:in `parsed_response'
	from /var/lib/gems/2.3.0/gems/gitlab-4.3.0/lib/gitlab/error.rb:39:in `build_error_message'
	from /var/lib/gems/2.3.0/gems/gitlab-4.3.0/lib/gitlab/error.rb:16:in `initialize'
	from /var/lib/gems/2.3.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:64:in `exception'
	from /var/lib/gems/2.3.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:64:in `raise'
	from /var/lib/gems/2.3.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:64:in `validate'
	from /var/lib/gems/2.3.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:44:in `block (2 levels) in <class:Request>'
	from /var/lib/gems/2.3.0/gems/gitlab-4.3.0/lib/gitlab/client/commits.rb:61:in `commit_comments'
	from /var/lib/gems/2.3.0/gems/pronto-0.9.5/lib/pronto/gitlab.rb:5:in `commit_comments'
	from /var/lib/gems/2.3.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `block in existing_comments'
	from /var/lib/gems/2.3.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `each'
	from /var/lib/gems/2.3.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `flat_map'
	from /var/lib/gems/2.3.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `existing_comments'
	from /var/lib/gems/2.3.0/gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:6:in `format'
	from /var/lib/gems/2.3.0/gems/pronto-0.9.5/lib/pronto.rb:67:in `block in run'
	from /var/lib/gems/2.3.0/gems/pronto-0.9.5/lib/pronto.rb:66:in `each'
	from /var/lib/gems/2.3.0/gems/pronto-0.9.5/lib/pronto.rb:66:in `run'
	from /var/lib/gems/2.3.0/gems/pronto-0.9.5/lib/pronto/cli.rb:61:in `block in run'
	from /var/lib/gems/2.3.0/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `chdir'
	from /var/lib/gems/2.3.0/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /var/lib/gems/2.3.0/gems/pronto-0.9.5/bin/pronto:6:in `<top (required)>'
	from /usr/local/bin/pronto:22:in `load'
	from /usr/local/bin/pronto:22:in `<main>'
```

**Comment by NARKOZ** [comment]
Should be fixed in version 4.5.0 via 2eb3a093419fcf367cbd19576c116febfbd17d2e
