### ISSUE TITLE
Last release (4.13.0) issue with HTTParty 0.17.2 dependency

### ISSUE THREAD

**Issue by chussenot** [NARKOZ/gitlab#536]
Fetching gem metadata from https://rubygems.org/............
Using gitlab 4.13.0

```
Traceback (most recent call last):
        15: from ./update:7:in `<main>'
        14: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/inline.rb:70:in `gemfile'
        13: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
        12: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
        11: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
        10: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
         9: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
         8: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `require'
         7: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/gitlab-4.13.0/lib/gitlab.rb:12:in `<top (required)>'
         6: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/gitlab-4.13.0/lib/gitlab.rb:12:in `require'
         5: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/gitlab-4.13.0/lib/gitlab/client.rb:3:in `<top (required)>'
         4: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/gitlab-4.13.0/lib/gitlab/client.rb:5:in `<module:Gitlab>'
         3: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/httparty-0.17.2/lib/httparty/module_inheritable_attributes.rb:7:in `block in initialize'
         2: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/httparty-0.17.2/lib/httparty/module_inheritable_attributes.rb:7:in `each'
         1: from /home/clementh/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/httparty-0.17.2/lib/httparty/module_inheritable_attributes.rb:9:in `block (2 levels) in initialize'
(eval):6:in `default_options=': undefined method `[]' for Thread:Class (NoMethodError)
```
The dependency breaks `bundle install`.

**Comment by chussenot** [comment]
* OS: debian
* Ruby: `2.6.3`

**Comment by giedriusr** [comment]
Same here

**Comment by rymai** [comment]
Reported in the `httparty` issue tracker: https://github.com/jnunemaker/httparty/issues/681. This is very weird.

**Comment by rymai** [comment]
Solved with `httparty` 0.17.3 now: https://github.com/jnunemaker/httparty/issues/681#issuecomment-566091726

**Comment by giedriusr** [comment]
Cool. This may be closed @chussenot

**Comment by NARKOZ** [comment]
Yes, that's an issue with httparty dependency.
