### ISSUE TITLE
version 4.14.0 breaks with "NoMethodError"

### ISSUE THREAD

**Issue by H3npi** [NARKOZ/gitlab#550]
Hi,

i am using this gem with danger.
The newest release (4.14.0) breaks with a "NoMethodError"
Stacktrace:

```
14:48:06 bundler: failed to load command: danger (/var/lib/jenkins/.rbenv/versions/2.3.1/bin/danger)
14:48:06 NoMethodError: undefined method `unpack1' for "/":String
14:48:06 Did you mean?  unpack
14:48:06   /var/lib/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.14.0/lib/gitlab/client.rb:81:in `block in url_encode'
14:48:06   /var/lib/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.14.0/lib/gitlab/client.rb:81:in `gsub'
14:48:06   /var/lib/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.14.0/lib/gitlab/client.rb:81:in `url_encode'
14:48:06   /var/lib/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.14.0/lib/gitlab/client/merge_requests.rb:43:in `merge_request'
14:48:06   /var/lib/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-6.3.1/lib/danger/request_sources/gitlab.rb:146:in `fetch_details'
14:48:06   /var/lib/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-6.3.1/lib/danger/danger_core/environment_manager.rb:52:in `fill_environment_vars'
14:48:06   /var/lib/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:266:in `run'
14:48:06   /var/lib/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-6.3.1/lib/danger/danger_core/executor.rb:29:in `run'
14:48:06   /var/lib/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-6.3.1/lib/danger/commands/runner.rb:73:in `run'
14:48:06   /var/lib/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
14:48:06   /var/lib/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-6.3.1/bin/danger:5:in `<top (required)>'
14:48:06   /var/lib/jenkins/.rbenv/versions/2.3.1/bin/danger:23:in `load'
14:48:06   /var/lib/jenkins/.rbenv/versions/2.3.1/bin/danger:23:in `<top (required)>'
```

**Comment by NARKOZ** [comment]
I see you're using Ruby 2.3. The support for Ruby 2.3 was dropped in 1ba41ec

**Comment by NARKOZ** [comment]
> I see you're using Ruby 2.3. The support for Ruby 2.3 was dropped in [1ba41ec](https://github.com/NARKOZ/gitlab/commit/1ba41ec1f37ecafb8393a30d78913423f60d7601)

This change will be reflected in gemspec https://github.com/NARKOZ/gitlab/blob/39f454e560f434cd0416d8ffcc1158404e659f59/gitlab.gemspec#L23

**Comment by H3npi** [comment]
Didn't noticed that change. Sorry! Upgrading to ruby 2.6.5 fixed the issue!
