### ISSUE TITLE
`download_job_artifact_file` method fails when the artifact is a non-JSON text file

### ISSUE THREAD

**Issue by balasankarc** [NARKOZ/gitlab#621]
When trying to download an artifact file using the `download_job_artifact_file`, the response is incorrectly attempted to be JSON-parsed, and hence will fail for any non-JSON non-binary files.

Example: Try downloading artifacts from https://gitlab.com/balasankarc/test-gitlab-gem-artifact-download/-/jobs/1399004917. See example below

```ruby
[1] pry(main)> valid_json_file = client.download_job_artifact_file(27906257, 1399004917, 'output/artifact.json')
=> #<Gitlab::FileResponse:46760 {filename: "artifact.json"}>

[2] pry(main)> jpg_file = client.download_job_artifact_file(27906257, 1399004917, 'output/artifact.jpg')
=> #<Gitlab::FileResponse:46780 {filename: "artifact.jpg"}>

[3] pry(main)> number_only_text_file = client.download_job_artifact_file(27906257, 1399004917, 'output/artifact.numbers.txt')
=> true

[4] pry(main)> string_text_file = client.download_job_artifact_file(27906257, 1399004917, 'output/artifact.txt')
Gitlab::Error::Parsing: The response is not a valid JSON
from /home/balasankarc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/gitlab-4.17.0/lib/gitlab/request.rb:37:in `rescue in decode'
Caused by JSON::ParserError: 809: unexpected token at 'HelloWorld'
from /home/balasankarc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/json-2.5.1/lib/json/common.rb:216:in `parse'

[5] pry(main)> invalid_json_file = client.download_job_artifact_file(27906257, 1399004917, 'output/artifact.invalid.json')
Gitlab::Error::Parsing: The response is not a valid JSON
from /home/balasankarc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/gitlab-4.17.0/lib/gitlab/request.rb:37:in `rescue in decode'
Caused by JSON::ParserError: 809: unexpected token at 'Random String which is not valid JSOn
'
from /home/balasankarc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/json-2.5.1/lib/json/common.rb:216:in `parse'
```

1. Valid JSON file worked
2. JPG file worked
3. Text file with only numbers [returned `true`](https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/request.rb#L25) because [JSON load failed and the `|| {}` gets applied](https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/request.rb#L35).
4. Text file with string raised an error as it was [attempted to be JSON parsed](https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/request.rb#L37)
5. Invalid JSOn file (which is technically same as a regular text file) raised an error as it was [attempted to be JSON parsed](https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/request.rb#L37)

**Comment by NARKOZ** [comment]
Download handles only binary files: https://github.com/NARKOZ/gitlab/blob/891fc6020868ee39eb0f98c144fba3eef82d3f97/lib/gitlab/client/jobs.rb#L120-L124

**Comment by pmgower** [comment]
I had this same issue while downloading a YAML coverage report from a GitLab CI job. Put up a fix in #738.

The non-binary path is reached for two cases — the `# error with json response` comment captures one. Error envelopes genuinely need `Gitlab::Request.parse` (used by `Gitlab::Error::ResponseError#initialize` to build the error message); successful text artifacts don't. The patch tries the JSON parse and falls back to `FileResponse` on `Gitlab::Error::Parsing` — preserves the error path and fixes the artifact path.

Same parser proc is duplicated across `job_artifacts_download`, `download_job_artifact_file`, and `download_branch_artifact_file`; PR patches all three.
