### ISSUE TITLE
Only on Ruby 3: wrong number of arguments (given 2, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by Nowaker** [NARKOZ/gitlab#627]
`projects = Gitlab.group_projects(43).auto_paginate` raises the below error on Ruby 3.0.2. Changing to Ruby 2.5.8 and the problem is gone.

```
/home/nowaker/.rvm/gems/ruby-3.0.2/gems/json-2.1.0/lib/json/common.rb:156:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from /home/nowaker/.rvm/gems/ruby-3.0.2/gems/json-2.1.0/lib/json/common.rb:156:in `new'
        from /home/nowaker/.rvm/gems/ruby-3.0.2/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
        from /home/nowaker/.rvm/gems/ruby-3.0.2/gems/json-2.1.0/lib/json/common.rb:335:in `load'
        from /home/nowaker/.rvm/gems/ruby-3.0.2/gems/gitlab-4.17.0/lib/gitlab/request.rb:35:in `decode'
        from /home/nowaker/.rvm/gems/ruby-3.0.2/gems/gitlab-4.17.0/lib/gitlab/request.rb:18:in `parse'
        from /home/nowaker/.rvm/gems/ruby-3.0.2/gems/gitlab-4.17.0/lib/gitlab/request.rb:12:in `block in <class:Request>'
        from /home/nowaker/.rvm/gems/ruby-3.0.2/gems/httparty-0.18.1/lib/httparty/request.rb:327:in `parse_response'
        from /home/nowaker/.rvm/gems/ruby-3.0.2/gems/httparty-0.18.1/lib/httparty/request.rb:295:in `block in handle_response'
        from /home/nowaker/.rvm/gems/ruby-3.0.2/gems/httparty-0.18.1/lib/httparty/response.rb:35:in `parsed_response'
        from /home/nowaker/.rvm/gems/ruby-3.0.2/gems/gitlab-4.17.0/lib/gitlab/request.rb:61:in `validate'
        from /home/nowaker/.rvm/gems/ruby-3.0.2/gems/gitlab-4.17.0/lib/gitlab/request.rb:51:in `block (2 levels) in <class:Request>'
        from /home/nowaker/.rvm/gems/ruby-3.0.2/gems/gitlab-4.17.0/lib/gitlab/client/groups.rb:185:in `group_projects'
        from /home/nowaker/.rvm/gems/ruby-3.0.2/gems/gitlab-4.17.0/lib/gitlab.rb:28:in `method_missing'
```

**Comment by NARKOZ** [comment]
I believe this isn't an issue with gem. We have specs that are passing on Ruby 3.0 https://github.com/NARKOZ/gitlab/blob/master/spec/gitlab/paginated_response_spec.rb

**Comment by Nowaker** [comment]
@NARKOZ I'll check when I'm back to work and let you know.
